apiVersion: v1
kind: Service
metadata:
  labels:
    run: gitea
  name: gitea-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    run: gitea
  type: NodePort
