apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
    app.kubernetes.io/instance: git-app
  name: gitea
  namespace: git
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app: gitea
  type: NodePort
