apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-nginx
  name: svc-web-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-nginx
  type: NodePort